### ISSUE TITLE
Does this support Teensy 3.2?

### ISSUE THREAD

**Issue by ajdupree** [apmorton/teensy-template#10]
Not sure how to set the right version in the makefile.

**Comment by apmorton** [comment]
I have not looked into 3.2 - but after a few minutes digging, it seems to be identical to 3.1 - except for a better voltage regulator?

You should be able to specify `TEENSY = 31` in your makefile

**Comment by ajdupree** [comment]
Yes, I've tried that! Seems to work fine now. Thank you.
