### ISSUE TITLE
Remove GCC toolchain

### ISSUE THREAD

**Issue by corny** [apmorton/teensy-template#18]
Do we really need the GCC toolchain inside of the repository? On Debian/Ubuntu the following command installs everything:
```
apt-get install gcc-arm-none-eabi
```

There might be similar packages for other distributions?

**Comment by apmorton** [comment]
I suppose not, but one of the initial goals was to be as portable as possible.  Additionally, without rewriting the entire git history of this repo, no space will be saved by removing the gcc toolchain at this point.  If you clone or fork it, the entire history comes with it, including all the binary files from before the toolchain got removed.

Austin

**Comment by corny** [comment]
Ok, but it's only portable if you stay on x86 64bit. The toolchain does not work on 32bit systems or ARM like the raspberry. I removed the toolchain from my local copy, but this is clearly no option for you.
